/* milter-spamc.h.  Generated by configure.  */
/***********************************************************************
 ***
 ***********************************************************************/

#define MILTER_NAME "milter-spamc"
#define MILTER_MAJOR 0
#define MILTER_MINOR 20
/* #undef MILTER_BUILD */
#define MILTER_AUTHOR "Anthony Howe <achowe@snert.com>"
#define MILTER_VERSION "milter-spamc/0.20." MILTER_BUILD_STRING
#define MILTER_COPYRIGHT "Copyright 2003, 2004 by Anthony Howe. All rights reserved."

#define STATEDIR "/var/milter-spamc"
#define RUN_AS_USER "smmsp"
#define RUN_AS_GROUP "smmsp"

#define HAVE_GETHOSTNAME 1
#define HAVE_GETHOSTBYNAME 1
/* #undef HAVE_GETHOSTBYNAME2 */

/* #undef DEFAULT_SPAM_LEVEL_CHARACTER */
/* #undef DEFAULT_HEADER_BUFFER_SIZE */

/* #undef TEST_ACCESS_DATABASE_FROM_TAG */
/* #undef TEST_ACCESS_DATABASE_TO_TAG */
#define MILTER_WITH_BERKELEY_DB 1

/***********************************************************************
 *** END
 ***********************************************************************/
